# Generated by Django 5.1.7 on 2025-04-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0002_studentidea_studentproject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentIdea',
        ),
    ]
