# Generated by Django 5.1.7 on 2025-04-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0003_delete_studentidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prototype',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
