# Generated by Django 5.1.7 on 2025-04-25 07:09

import project_repo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_repo', '0008_evaluation_project_id_evaluation_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='academic_year',
            field=models.CharField(default=project_repo.models.get_current_academic_year, max_length=10),
        ),
    ]
